FROM golang:1.17.5-alpine

WORKDIR /app

# Copy and download dependency using go mod
ENV GO111MODULE=on
COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

# Build the binary
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
      -v -o bin/http cmd/http/*.go

RUN apk add --no-cache supervisor
RUN apk add --update coreutils && rm -rf /var/cache/apk/*

CMD ["/bin/sh","docker-entrypoint.sh"]
